#!/bin/sh

rm -f bin/testsockets.o
rm -f bin/testsockets

/usr/local/bin/nasm -g -f macho64 testsockets.asm    -o bin/testsockets.o &&
/usr/local/bin/nasm -g -f macho64 printing.asm -o bin/printing.o &&
/usr/local/bin/nasm -g -f macho64 numbers.asm -o bin/numbers.o &&

ld bin/testsockets.o bin/printing.o bin/numbers.o -lc -arch x86_64 -macosx_version_min 10.7.0 -no_pie -lSystem -o bin/testsockets

